Update the urlllib3 package dependency to make it compatible with v2
qdrant/qdrant-client pull request #418
Opened 2024-01-03 12:12 UTC by lingcoder

### All Submissions:

* [ ] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you installed `pre-commit` with `pip3 install pre-commit` and set up hooks with `pre-commit install`?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-01-06 01:53 UTC, joein commented
I believe it won't work, since `^1.26.4` is equal to `>=1.26.4,<2.0.0`

Instead, it should be `urllib3 = ">=1.26.14,<3"`

2024-01-07 23:24 UTC, lingcoder commented
> I believe it won't work, since `^1.26.4` is equal to `>=1.26.4,<2.0.0`
> 
> Instead, it should be `urllib3 = ">=1.26.14,<3"`



> 我相信这是行不通的，因为`^1.26.4`等于`>=1.26.4,<2.0.0`
> 
> 相反，它应该是`urllib3 = ">=1.26.14,<3"`

It's truly what I committed. `urllib3 = ">=1.26.14,<3`

2024-01-08 08:39 UTC, joein commented
To enable installation of v2+, this dependency should be changed to ">1.26.4,<3", do you want to do it or should I take over?

2024-01-08 10:05 UTC, lingcoder commented
> To enable installation of v2+, this dependency should be changed to ">1.26.4,<3", do you want to do it or should I take over?

Oh, my apologies, I finally understand where I went wrong. I have submitted the latest PR, and it would be my honor to contribute code to qdrant.

2024-01-08 11:21 UTC, joein requested changes

2024-01-08 11:21 UTC, joein commented on pyproject.toml
> +urllib3 = ">1.26.4,<3"
```suggestion
urllib3 = ">=1.26.4,<3"
```

2024-01-08 19:21 UTC, joein approved these changes

2024-01-08 19:21 UTC, merged