Nirant/upgrade-fastembed-version
qdrant/qdrant-client pull request #493
Opened 2024-02-15 04:24 UTC by NirantK

### All Submissions:

* [ ] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you installed `pre-commit` with `pip3 install pre-commit` and set up hooks with `pre-commit install`?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-02-15 12:02 UTC, joein requested changes

2024-02-15 12:02 UTC, joein commented on qdrant_client/qdrant_fastembed.py
> +    DEFAULT_EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"
We need to make at least one major release which warns that we are going to change the model

2024-02-15 12:02 UTC, joein commented on qdrant_client/qdrant_fastembed.py
> -    "BAAI/bge-base-en": (768, models.Distance.COSINE),
we can't just silently remove models which could have already been used by users

2024-03-02 23:06 UTC, joein commented
We need to fix our tests to run them without fastembed installed as well

2024-03-03 01:05 UTC, joein commented
#522

2024-03-05 18:39 UTC, generall approved these changes

2024-03-05 20:09 UTC, joein approved these changes

2024-03-05 20:09 UTC, merged