V1.9.x
qdrant/qdrant-client pull request #608
Opened 2024-04-18 15:18 UTC by generall

Update models and conversion for compatibility with Qdrant Server v1.9.x

2024-04-18 15:25 UTC, generall commented
Depends on: 
- https://github.com/qdrant/qdrant-client/pull/600
- https://github.com/qdrant/qdrant-client/pull/601

2024-04-18 20:00 UTC, SamirPS requested changes

2024-04-19 09:23 UTC, joein commented
todo: change qdrant latest version in integration tests to 1.9.0 once it is released

2024-04-22 11:15 UTC, SamirPS approved these changes

2024-04-22 12:28 UTC, merged