added new to type stub + fixed type hinting
qdrant/qdrant-client pull request #717
Opened 2024-08-05 08:24 UTC by hh-space-invader

### All Submissions:

* [ ] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you installed `pre-commit` with `pip3 install pre-commit` and set up hooks with `pre-commit install`?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-08-05 08:40 UTC, hh-space-invader commented
#696
#687

2024-08-06 18:14 UTC, joein commented
other than the comments, looks fine

2024-08-07 09:18 UTC, joein requested changes

2024-08-08 08:06 UTC, joein commented
could you please regenerate poetry.lock

2024-08-08 10:56 UTC, joein requested changes

2024-08-08 10:56 UTC, joein commented on qdrant_client/conversions/common_types.py
> +Points = Union[rest.Batch, Sequence[Union[rest.PointStruct, grpc.PointStruct]]]
`LocalCollection.upsert` should become `Union[Sequence[models.PointStruct], models.Batch]` then

2024-08-08 15:44 UTC, joein approved these changes

2024-08-08 15:44 UTC, merged