chore: Update clients
qdrant/qdrant-client pull request #758
Opened 2024-08-27 16:08 UTC by coszio

Updates clients with the latest dev changes.

For grpc I could not install `grpcio==1.48.2`, so I updated it with `grpcio==1.65.4`

New stuff:
- facets
- distance matrix
- misc

2024-08-29 05:27 UTC, joein commented
@coszio 

what was the problem with grpcio?
1.48.2 works fine for me

using 1.49.1 brings type checker issues :(

2024-08-29 22:12 UTC, coszio commented
I believe what we need is to pin the `grpcio-tools` version to 1.48.2, but not necessarily for `grpcio`. 

In my computer trying to build `grpcio==1.48.2` fails every time, by relaxing this one, I could generate correctly, as far as I can tell

2024-09-02 12:51 UTC, joein commented on tools/generate_grpc_client.sh
> +pip install grpcio-tools==1.48.2 # the expected python version to use is 1.10.10
```suggestion
pip install grpcio-tools==1.48.2 # the expected python version to use is 3.10.10
```

2024-09-03 05:49 UTC, joein approved these changes

2024-09-03 20:45 UTC, generall requested changes
Please generate grpc with original version of `grpcio`

Do not change the version.

2024-09-04 17:16 UTC, generall approved these changes

2024-10-05 21:03 UTC, merged