Tsk 757 add support for tuple in payload
qdrant/qdrant-client pull request #763
Opened 2024-09-02 10:18 UTC by hh-space-invader

### All Submissions:

* [ ] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you installed `pre-commit` with `pip3 install pre-commit` and set up hooks with `pre-commit install`?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-09-02 11:13 UTC, joein requested changes

2024-09-02 11:13 UTC, joein commented on tests/congruence_tests/test_payload.py
> +        {"listvalue": [1, 1]},
Could we maybe add it to the random payload generator in fixtures?

2024-09-03 20:55 UTC, generall commented
why do we need this?

2024-09-04 10:33 UTC, joein commented
@generall 
1) mostly for the congruence, it works this way with http
2) there is a request https://github.com/qdrant/qdrant-client/issues/757 , according to which we used to provide such a behaviour earlier

2024-09-09 08:41 UTC, joein approved these changes

2024-09-13 15:19 UTC, merged