User warnings large upload
qdrant/qdrant-client pull request #852
Opened 2024-11-15 09:12 UTC by hh-space-invader

Add user warnings if uploading or loading collection with more than 20K points in local mode.
I've refactored the way we do DeprecationWarning as we also want to add  UserWarning to be shown once by adding  show_warning and show_warning_once and then specify the category of the warning needed to be shown once.

### All Submissions:

* [ ] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you installed `pre-commit` with `pip3 install pre-commit` and set up hooks with `pre-commit install`?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-11-15 09:41 UTC, joein requested changes

2024-11-15 09:41 UTC, joein commented on qdrant_client/common/deprecations.py
> +def deprecation_warning_once(message: str, idx: Optional[str] = None) -> None:
why?

2024-11-15 09:41 UTC, joein commented on qdrant_client/local/local_collection.py
> +            deprecation_warning_once(
it's not a `deprecation` warning

2024-11-15 09:41 UTC, joein commented on qdrant_client/local/local_collection.py
> +                f"Local mode is not recommended for collections with more than {self.LARGE_DATA_THRESHOLD:,} points. Consider using Qdrant server mode for better performance with large datasets.",
It's probably unclear what is `server` mode, let's write about hosting qdrant in docker or using cloud

2024-11-15 09:41 UTC, joein commented on qdrant_client/local/local_collection.py
> +                )
it's not about the amount of points they're trying to upsert with one call, it's about the amount of points in the collection in general

2024-11-22 07:54 UTC, joein requested changes

2024-11-25 08:59 UTC, generall commented on qdrant_client/common/client_warnings.py
> +        show_warning(message, category)
```suggestion
        show_warning(message, category)
        
def deprecation_warning(message: str) -> None:
    show_warning(message, DeprecationWarning)


def deprecation_warning_once(message: str, idx: Optional[str]) -> None:
    show_warning_once(message, DeprecationWarning, idx)
```

Changes of unrelated methods could be avoided if you just add those

2024-12-03 13:01 UTC, joein requested changes

2024-12-03 13:01 UTC, joein commented on qdrant_client/local/local_collection.py
> +        )
I would even suggest removing this check and just check collection size in the end of the method
1) It is easier just to check len(self.ids) in the end
2) upsert can contain points with the same ids which will not lead to exceeding `self.LARGE_DATA_THRESHOLD`

2024-12-03 13:01 UTC, joein commented on qdrant_client/local/async_qdrant_local.py
> +                            message=f"Local mode is not recommended for collections with more than {self.LARGE_DATA_THRESHOLD:,} points. Consider using Qdrant docker (http/grpc) or Qdrant cloud for b
same for the others

2024-12-05 11:53 UTC, joein approved these changes

2024-12-05 12:01 UTC, merged