feat: Send client version to server in headers
qdrant/qdrant-client pull request #861
Opened 2024-12-02 09:27 UTC by tellet-q

Use headers (User-Agent for http and user-agent for grpc) to pass client's version to server. 

### All Submissions:

* [X] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [X] Have you installed `pre-commit` with `pip3 install pre-commit` and set up hooks with `pre-commit install`?

### Changes to Core Features:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-12-03 10:02 UTC, joein requested changes

2024-12-03 10:02 UTC, joein commented on qdrant_client/async_qdrant_remote.py
> +from packaging import version
why do we need it in the first place?

importlib.metadata.version returns a string which should be acceptable, are there any corner cases?

2024-12-03 10:13 UTC, tellet-q commented on qdrant_client/async_qdrant_remote.py
> +from packaging import version
The `packaging` is a dependency for many other deps in the poetry.lock, so I felt safe to import it. But you are right, for this particular PR a simple string from `importlib.metadata.version` is enough.

2024-12-03 10:20 UTC, joein commented on qdrant_client/async_qdrant_remote.py
> +from packaging import version
when you create a fresh environment and install only `qdrant-client` there, `packaging` is not available

2024-12-03 12:16 UTC, joein approved these changes

2024-12-04 21:46 UTC, joein approved these changes

2024-12-05 07:08 UTC, merged